apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: indeed.csi.k8s.io
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed.csi.k8s.io
    app.kubernetes.io/component: csi-driver
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  fsGroupPolicy: File
