kind: ServiceAccount
apiVersion: v1
metadata:
  name: indeed-csi-sa
  namespace: default
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: attacher-cluster-role
  name: indeed-csi-attacher-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: health-monitor-controller-cluster-role
  name: indeed-csi-health-monitor-controller-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-health-monitor-controller-runner
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: provisioner-cluster-role
  name: indeed-csi-provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: resizer-cluster-role
  name: indeed-csi-resizer-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-resizer-runner
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: snapshotter-cluster-role
  name: indeed-csi-snapshotter-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-snapshotter-runner
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: attacher-role
  name: indeed-csi-attacher-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-attacher-cfg
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: health-monitor-controller-role
  name: indeed-csi-health-monitor-controller-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-health-monitor-controller-cfg
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: provisioner-role
  name: indeed-csi-provisioner-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: resizer-role
  name: indeed-csi-resizer-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-resizer-cfg
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: indeed.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-indeed
    app.kubernetes.io/name: indeed-csi
    app.kubernetes.io/component: snapshotter-role
  name: indeed-csi-snapshotter-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-snapshotter-leaderelection
subjects:
- kind: ServiceAccount
  name: indeed-csi-sa
---