kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
  - name: my-frontend
    image: busybox
    volumeMounts:
    - mountPath: "/data"
      name: my-csi-volume
    command: [ "sleep", "1000000" ]
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 200m
        memory: 2Gi
  volumes:
  - name: my-csi-volume
    persistentVolumeClaim:
      claimName: csi-pvc
